### ISSUE TITLE
FusionCMS 9.1.1 - Character not Showing on specific realm

### ISSUE THREAD

**Issue by TheFrozenThr0ne** [Karitoswow/levelup#1]
Somehow the character does not appear in the list. But i have one on 3.3.5 (12340) as you can see at the right side of the screen.

![image](https://github.com/user-attachments/assets/c011cfb9-2fb6-45c2-a5b1-72522a33457b)

**Comment by Karitoswow** [comment]
Your character level is 80! This module is used for sublevel below 80

**Comment by TheFrozenThr0ne** [comment]
My bad. Thank you for the hint. Didnt read until now.
